// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online_BookStore.Data;

#nullable disable

namespace Online_BookStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Online_BookStore.Models.Category", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_ID = 1,
                            Category_Name = "Fiction"
                        },
                        new
                        {
                            Category_ID = 2,
                            Category_Name = "Romance"
                        },
                        new
                        {
                            Category_ID = 3,
                            Category_Name = "Mystery/Thriller"
                        },
                        new
                        {
                            Category_ID = 4,
                            Category_Name = "Classics"
                        },
                        new
                        {
                            Category_ID = 5,
                            Category_Name = "Fiction"
                        },
                        new
                        {
                            Category_ID = 6,
                            Category_Name = "Romance"
                        },
                        new
                        {
                            Category_ID = 7,
                            Category_Name = "Mystery/Thriller"
                        },
                        new
                        {
                            Category_ID = 8,
                            Category_Name = "Classics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
